package com.fdmgroup.main;

public enum Event {
	NO_OBSTACLES,
	OBSTACLE_LEFT,
	OBSTACLE_FRONT,
	OBSTACLE_RIGHT,
	OBSTACLES_LEFT_FRONT,
	OBSTACLES_LEFT_RIGHT,
	OBSTACLES_FRONT_RIGHT,
	OBSTACLES_ALL,
	TERMINATE;
}
